### ISSUE TITLE
I've tried and it doesn't work

### ISSUE THREAD

**Issue by cdecompilador** [pdf-rs/fax#2]
Is the decoding fully implemented? I couldn't decode to pbm using the example (and fixing the error it had on `decode_g4`)

**Comment by s3bk** [comment]
I don't think it is fully implemented.
I tried to follow the specification as much as I could. If you know other documentation it might be possible to get more working.

**Comment by cdecompilador** [comment]
I'm not too much into this, I just wanted to decode the image data extracted with `lopdf` for a cli app, I'll keep this open just in case someone wants to fix it

**Comment by maxpowel** [comment]
I'm having some issues with some files. 
Due problems with name extensions in github, I added an example with a zip file containing the following content:
[stream.zip](https://github.com/pdf-rs/fax/files/14237386/stream.zip)
* 4 -> the raw content extracted from a PDF
* 4.pbm > the file processed by this crate
* 4.tif -> the file processed with `fax2tiff`

The application `fax2tiff` is generating a valid file while `fax` is creating something corrupted (but still visible and you can see that some parts look correct)

The exact call to `fax2tiff` is: `fax2tiff -4 -X 360 -M 4 -o 4.tif` where:
* -4 is the format to use (group 4)
* -X the width (360 in this case)
* -M is `input data has MSB2LSB bit order` (default value is LSB2MSB)
* -o the output file



In case this information could be interesting, this file was (based on the PDF data) generated by the printer Canon iR-ADV. Many images from these PDF are being generated perfectly so I think that these `not implemented` parts are affecting here.

The is the source code of the program `fax2tiff` https://github.com/vadz/libtiff/blob/master/tools/fax2tiff.c
I'm reading both code (fax crate and tax2tiff) in order to find these missing parts.

**Comment by s3bk** [comment]
Yea, there are bugs remaining that I could not figure out using the specification.
I will take a look at the fax2tiff. However tiff supports the fax encoding, so it might just add the correct header.

**Comment by s3bk** [comment]
It was an easy fix. Just took a while to figure out where!

**Comment by maxpowel** [comment]
Thak you so much!
